### ISSUE TITLE
Loosen click dependency

### ISSUE THREAD

**Issue by adriangb** [RonquilloAeon/migri#49]
black 22 depends on click 8, but this package requires click < 8 and hence can't be used with the only stable version of black. I suggest that you bump up the version.

**Comment by RonquilloAeon** [comment]
I plan to spend time within the next few days reviewing issues and getting a minor version out. I'll look into this then. If you are able to work on it sooner, I'll gladly review your PR!

**Comment by adriangb** [comment]
Would you consider making the CLI optional? Like `migri[cli]`?

**Comment by RonquilloAeon** [comment]
Hmm let me think on it. That shouldn't be an issue. Your suggestion makes sense for cases where migri will only be used programmatically.

**Comment by adriangb** [comment]
Yeah another option, if you wanted to keep the current behavior, is to publish `migri-core` and `migri` or something. But I think asking users to install `migri[cli]` isn't too bad given that they already have to install an extra for their database driver.

**Comment by RonquilloAeon** [comment]
I like your first suggestion better than creating a second package. I'll fix the click version issue and I'll open a new issue for making click optional.

**Comment by RonquilloAeon** [comment]
@adriangb done. CI is building and `v0.7.0` will be published shortly. Thank you for all your help!
