### ISSUE TITLE
Merge init and migrate commands

### ISSUE THREAD

**Issue by RonquilloAeon** [RonquilloAeon/migri#7]
An idea to consolidate `init` and `migrate` commands into one to make migri usage more concise. Anyway, `migrate` is useless w/out `init`. We may want to have an optional flag to only migrate if migri has been initialized, but I haven't thought of a case where this would be necessary.

**Comment by zbarnett** [comment]
`merge` command or `migrate` command?

**Comment by RonquilloAeon** [comment]
> `merge` command or `migrate` command?

Ha good call! My mind got stuck on `merge`. Edited my comment.

**Comment by RonquilloAeon** [comment]
Handled in #20 along with issue #12
